### ISSUE TITLE
Add query condition for "Project: Last Logged Event"

### ISSUE THREAD

**Issue by shichikoromo** [IUREDCap/auto-notify-module#3]
Is it possible to add a query condition for "Project: Last Logged Event"?

Example query:
```sql
SELECT project_id, project_name, last_logged_event FROM redcap_projects;
```

It would be helpful to notify users of inactive projects.

**Comment by mullen2** [comment]
@shichikoromo Thanks for the feedback. I will try to get that added soon.

**Comment by mullen2** [comment]
@shichikoromo a new version (1.5.9) was just added to the external module repository that has the new "Project Last Logged Event" query condition variable.
